/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "CortexM3_Core_NVIC.h"
#include "CortexM3_Core_SysTick.h"
#include "SCB.h"
#include "Std_Types.h"
#include "BIT_MATH.h"
#include "FPEC_interface.h"
#include "FPEC_config.h"
#include "FPEC_private.h"
#include "GPIO.h"
#include "DMA.h"
#include "RCC_interface.h"
#include "CAN_interface.h"
#include "LED_interface.h"

uint8_t RetVal = 0;
volatile uint32_t MainAppCounter = 0;
volatile uint32_t MainAppCounter_Double_Interval = 0;
static volatile uint8_t USART3_IRQHandler_Flag = 0;
static volatile uint8_t USART3_IRQHandler_Active_Flag1 = 0;
static volatile uint8_t USART3_IRQHandler_Active_Flag2 = 0;
static uint32_t PriorityGroupingValue = 0;
static uint16_t test_flash_write = 130;

uint8_t RxData[8];
uint8_t TxData[8];
CAN_RxHeaderTypeDef Rx_header;
uint32_t TxMailbox;

void SysTickFun_1(void){
	MainAppCounter_Double_Interval++;
}

/*void CAN_RxFifo0MsgPendingCallback(){
	CAN_voidGetRxMsg(CAN_RX_FIFO0, &RxHeader, RxData);
}*/

int main(void)
{
	/* NVIC Test Start ---------------------------------------------------------
	// NVIC_EnableIRQ(USART3_IRQn);      // in ISER1
	// NVIC_EnableIRQ(EXTI15_10_IRQn);
	// NVIC_EnableIRQ(RTCAlarm_IRQn);

	// NVIC_DisableIRQ(USART3_IRQn);
	// NVIC_DisableIRQ(EXTI15_10_IRQn);
	// NVIC_DisableIRQ(RTCAlarm_IRQn);

	// NVIC_SetPendingIRQ(USART3_IRQn);

	// SCB_SetPriorityGrouping(SCB_PRIORITYGROUP_2 );
	// PriorityGroupingValue = SCB_GetPriorityGrouping();
	// NVIC_SetPriority(USART3_IRQn, 4);
	NVIC Test End ----------------------------------------------------------- */

	/* SysTick Testing Start --------------------------------------------------
	// RetVal =  SysTick_Init(1000000);
	// SysTick_SingleInterval(1000000, SysTickFun_1);
	// SysTick_PeriodicInterval(1000000, SysTickFun_1);
	SysTick Testing End ------------------------------------------------------ */

	/* Flash Testing Start ---------------------------------------------------
	 FPEC_voidInit();
	 FPEC_voidFlashWriteHalfWord(0x0801FC00, test_flash_write);
	 FPEC_voidFlashPageErase(127);
	Flash Testing End ------------------------------------------------------ */

	/* RCC & GPIO Testing Start ---------------------------------------------
	 RCC_voidInitSysClock();
	 RCC_voidEnableClock(RCC_APB2, 4);
	 GPIO_voidSetPinDirection(GPIOC, PIN13, OUTPUT_SPEED_10MHZ_PP);
	RCC & GPIO Testing Start --------------------------------------------- */

	CAN_voidInit();
	CAN_FilterConfig();
//	CAN_Interrupt();
	CAN_voidStart();

	while(1){
		 //USART3_IRQHandler_Active_Flag1 = NVIC_GetActive(USART3_IRQn);
		 //SysTick_WaitBlocking(1000000);
		 //MainAppCounter++;
		 //SysTick_SingleInterval(1000000, SysTickFun_1);



		// LED_voidLed_Toggle(GPIOC, PIN13);
		// SysTick_WaitBlocking(1000000);


		CAN_TX();
		CAN_RX();
		SysTick_WaitBlocking(1000000);


	}
}

void USART3_IRQHandler(void){
	USART3_IRQHandler_Flag = 1;
	USART3_IRQHandler_Active_Flag2 = NVIC_GetActive(USART3_IRQn);
}


void CAN_TX(void)
{
	CAN_TxHeaderTypeDef tx_header;
	tx_header.StdId = 0x103;
	tx_header.IDE = CAN_ID_STD;
	tx_header.RTR = CAN_RTR_DATA;
	tx_header.DLC = 1;
	tx_header.TransmitGlobalTime= DISABLE;
	TxData[0] = 0xf3;

	CAN_voidAddTxMsg(&tx_header,TxData);
	CAN_voidEnableInterrupt(CAN_IER_RX_FIFO0_MSG_PENDING);
}


 void CAN_RX(void)
{
	CAN_RxHeaderTypeDef Rx_header;
	//while(CAN_voidRXPending(CAN_RX_FIFO0) == 0);
	uint8 DATA[5];
	CAN_voidGetRxMsg(CAN_RX_FIFO0,&Rx_header,DATA);
}

void CAN_RxFifo0MsgPendingCallback()
{
	CAN_RX();

}

void CAN_FilterConfig(void)
{
	CAN_FilterTypeDef CAN_FilterInit;
	CAN_FilterInit.FilterActivation = ENABLE;
	CAN_FilterInit.FilterBank = 0;
	CAN_FilterInit.FilterFIFOAssignment = CAN_FILTER_FIFO0;
	CAN_FilterInit.FilterIdHigh = 0x103<<5;
	CAN_FilterInit.FilterIdLow = 0x0000;
	CAN_FilterInit.FilterMaskIdHigh = 0x0000;
	CAN_FilterInit.FilterMaskIdLow = 0x0000;
	CAN_FilterInit.FilterMode = CAN_FILTERMODE_IDMASK;
	CAN_FilterInit.FilterScale = CAN_FILTERSCALE_32BIT;

	CAN_voidConfigFilter(&CAN_FilterInit);
}

void CAN_Interrupt(void)
{
	CAN_voidInitInterput(CAN_TX_IRQn);
	CAN_voidInitInterput(CAN_RX0_IRQn);
	CAN_voidInitInterput(CAN_RX1_IRQn);
	CAN_voidInitInterput(CAN_SCE_IRQn);

	CAN_voidEnableInterrupt(CAN_IER_TX_MAILBOX_EMPTY | CAN_IER_RX_FIFO0_MSG_PENDING | CAN_IER_ERROR | CAN_IER_LAST_ERROR_CODE | CAN_IER_BUSOFF);
}

